const resources = [
  {category:'reference',label:'Reference · PDF',title:'SAE Levels of Driving Automation (0–5)',description:'Official SAE International visual chart (2021): driver responsibilities and feature capabilities at each level.',url:'https://www.sae.org/binaries/content/assets/cm/content/blog/sae-j3016-visual-chart_5.3.21.pdf'},
  {category:'datasets',label:'Dataset',title:'KITTI Vision Benchmark',description:'Camera, LiDAR, and calibration data for projection and 3D detection practice.',url:'https://www.cvlibs.net/datasets/kitti/'},
  {category:'datasets',label:'Dataset',title:'nuScenes devkit tutorial',description:'Explore multi-camera, LiDAR, and radar data; start with the mini split.',url:'https://www.nuscenes.org/tutorials/nuscenes_tutorial.html'},
  {category:'datasets',label:'Dataset',title:'Waymo Open Dataset',description:'Large-scale perception and motion data; review the terms before downloading.',url:'https://waymo.com/open/'},
  {category:'datasets',label:'Dataset',title:'Argoverse 2 User Guide',description:'Official guide to sensor, map, and motion forecasting datasets.',url:'https://argoverse.github.io/user-guide/'},
  {category:'perception',label:'Perception',title:'OpenPCDet',description:'LiDAR 3D object detection toolbox with model configurations and tutorials.',url:'https://github.com/open-mmlab/OpenPCDet'},
  {category:'perception',label:'Perception',title:'MMDetection3D',description:'3D detection and multimodal perception framework with model and data guides.',url:'https://mmdetection3d.readthedocs.io/en/latest/'},
  {category:'simulation',label:'Simulation & systems',title:'CARLA Simulator',description:'Generate camera, LiDAR, and driving scenarios; match the docs to your version.',url:'https://carla.readthedocs.io/'},
  {category:'simulation',label:'Simulation & systems',title:'Autoware Documentation',description:'Architecture, modules, and deployment for an open-source driving stack.',url:'https://docs.autoware.org/main/home/'},
  {category:'courses',label:'Course',title:'University of Toronto · Self-Driving Cars',description:'A structured introduction to localization, perception, planning, and control.',url:'https://www.coursera.org/specializations/self-driving-cars/'}
];
const list=document.querySelector('#resource-list');
if(list){const render=(filter)=>{list.replaceChildren();for(const item of resources.filter(x=>filter==='all'||x.category===filter)){const a=document.createElement('a');a.className='resource';a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';const tag=document.createElement('span');tag.className='resource-tag';tag.textContent=item.label;const content=document.createElement('div');content.className='resource-content';const title=document.createElement('h3');title.textContent=item.title;const desc=document.createElement('p');desc.textContent=item.description;content.append(title,desc);const arrow=document.createElement('span');arrow.className='resource-arrow';arrow.setAttribute('aria-hidden','true');arrow.textContent='↗';a.append(tag,content,arrow);list.append(a)}};render('all');document.querySelector('#resource-count').textContent=`${resources.length.toString().padStart(2,'0')} links`;document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});render(button.dataset.filter)}))}document.querySelectorAll('#year').forEach(e=>e.textContent=new Date().getFullYear());
